export const CONFIG = {
  player: {
    height: 1.7,
    moveSpeed: 5,
    jumpForce: 5,
    gravity: 15,
    turnSpeed: 2,
    maxHealth: 100,
  },
  saber: {
    bladeLength: 1.2,
    bladeRadius: 0.015,
    glowRadius: 0.035,
    hiltLength: 0.3,
    playerColor: 0x00aaff,
    enemyColor: 0xff3333,
    lightIntensity: 2,
    lightDistance: 3,
    rotationSmoothing: 12,
    maxTiltAngle: Math.PI / 2.5,
    maxSwingAngle: Math.PI / 3,
  },
  combat: {
    minSwingSpeed: 0.02,
    clashDistance: 0.12,
    hitRadius: 0.08,
    damage: 10,
    blockThreshold: 0.15,
  },
  camera: { fov: 75, near: 0.1, far: 1000, mouseSensitivity: 0.002 },
  arena: {
    radius: 15,
    pillarCount: 8,
    pillarDistance: 12,
    backgroundColor: 0x87ceeb,
    fogDensity: 0.005,
  },
  physics: { sparkCount: 20, sparkLifetime: 1 },
  ai: {
    reactionTime: 0.3,
    aggressiveness: 0.6,
    blockSkill: 0.7,
    attackRange: 2.5,
    preferredDistance: 1.8,
    moveSpeed: 3,
    turnSpeed: 3,
  },
  network: {
    serverUrl: "ws://localhost:3000",
    updateRate: 50,
    interpolationDelay: 100,
  },
}
